baseURL = "https://edgarpachec0.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "BitÃ¡cora de Viaje de Edgar Pacheco"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "@Edg4rPache"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
